Ext.define('gfi.bin.admctasweb.model.r29.Manual', {
	extend: 'Ext.data.Model',
	
	fields: [
		 {name	: 'idEmpresa',				type	: 'string'},
		 {name	: 'txPersonaCoti',			type	: 'string'},
		 {name	: 'txPersonaTitular',		type	: 'string'},
		 {name	: 'txTipoNivel',			type	: 'string'},
		 {name	: 'txSucursal',				type	: 'string'},
		 {name	: 'txModalidad',			type	: 'string'},
		 {name	: 'txProducto',				type	: 'string'},
		 {name	: 'txMonedaAsegurada',		type	: 'string'},
		 {name	: 'cvePeriodo',				type	: 'string'},
		 {name	: 'descPeriodo',			type	: 'string'},
		 {name	: 'numIntento',				type	: 'string'},
		 {name	: 'situacion',				type	: 'string'},
		 {name	: 'institucion',			type	: 'string'},	         
		 {name	: 'medioSolicitado',		type	: 'string'},
		 {name	: 'autoridad',				type	: 'string'},
		 {name	: 'descripcion',			type	: 'string'},
		 {name	: 'numOficio',				type	: 'string'},
		 {name	: 'tipoOficio',				type	: 'string'},
		 {name	: 'fechaSolicitud',			type	: 'string'},
		 {name	: 'folioSiara',				type	: 'string'},
		 {name	: 'montoSolicitado',		type	: 'string'},	         
		 {name	: 'persoTitular',			type	: 'string'},
		 {name	: 'caracTitular',			type	: 'string'},
		 {name	: 'rfcTitular',				type	: 'string'},
		 {name	: 'razonTitular',			type	: 'string'},
		 {name	: 'nombreTitular',			type	: 'string'},
		 {name	: 'paternoTitular',			type	: 'string'},
		 {name	: 'maternoTitular',			type	: 'string'},
		 {name	: 'idCotitular',			type	: 'int'},
         {name	: 'persoCoti',				type	: 'int'},
         {name	: 'caracCoti',				type	: 'string'},
         {name	: 'rfcCoti',				type	: 'string'},
		 {name	: 'razonCoti',				type	: 'string'},
		 {name	: 'nombreCoti',				type	: 'string'},
		 {name	: 'paternoCoti',			type	: 'string'},
		 {name	: 'maternoCoti',			type	: 'string'},
		 {name	: 'idSucursal',				type	: 'string'},
		 {name	: 'estado',					type	: 'int'},
		 {name	: 'localidad',				type	: 'int'},
		 {name	: 'codigoPostal',			type	: 'string'},
		 {name	: 'modalidad',				type	: 'string'},
		 {name	: 'tipoNivel',				type	: 'string'},
		 {name	: 'idCuenta',				type	: 'string'},		 
		 {name	: 'producto',				type	: 'string'},
		 {name	: 'monedaCuenta',			type	: 'string'},
		 {name	: 'montoInicial',			type	: 'string'},
		 {name	: 'operacion',				type	: 'string'},
		 {name	: 'oficioReqOpe',			type	: 'string'},		 
		 {name	: 'fecharRequerimiento',	type	: 'string'},
		 {name	: 'siaraIndirecto',			type	: 'string'},		 
		 {name	: 'fechaAplicacion',		type	: 'string'},
		 {name	: 'montoOperacion',			type	: 'string'},	 
		 {name	: 'monedaOperacion',		type	: 'string'},
		 {name	: 'saldoOperacion',			type	: 'string'}

	],

    validations: [
         {type: 'presence', field: 'institucion',			message: 'La Institución es requerida'},
		 {type: 'presence', field: 'cvePeriodo', 			message: 'El Perriodo es requerido'},
		 {type: 'presence', field: 'autoridad', 			message: 'La Auroridad es requerida'},
		 {type: 'presence', field: 'numOficio',			 	message: 'El Número de Oficio es requerido'},
//		 {type: 'presence', field: 'tipoOficio',			message: 'El Tipo de Oficio es requerido'},
		 {type: 'presence', field: 'fechaSolicitud',		message: 'La Fecha de Solicitud es requerida'},
		 {type: 'presence', field: 'montoSolicitado',		message: 'El Monto Solicitado es requerido'},
//		 {type: 'presence', field: 'persoTitular',			message: 'El Tipo de Persona es requerido'},	         
//		 {type: 'presence', field: 'caracTitular',			message: 'El Caracter del Titular es requerido'},
//		 {type: 'presence', field: 'rfcTitular',			message: 'El RFC del Titular es requerido'},	         
//	     {type: 'presence', field: 'idCotitular',			message: 'El Nombre de Atención es requerido'},
//	     {type: 'presence', field: 'persoCoti',				message: 'El Tipo de Persona del Cotitular es requerido'},
//	     {type: 'presence', field: 'caracCoti',				message: 'El Caracterr del Cotitular es requerido'},
//	     {type: 'presence', field: 'rfcCoti',				message: 'El RFC del Cotitular es requerido'},
	     {type: 'presence', field: 'idSucursal',			message: 'El Número de Sucursal es requerido'},
	     {type: 'presence', field: 'modalidad',			    message: 'La Modalidad es requerida'},
	     {type: 'presence', field: 'tipoNivel',				message: 'El Tipo de Nivel es requerido'},
	     {type: 'presence', field: 'idCuenta',				message: 'El Número de Cuenta es requerido'},
	     {type: 'presence', field: 'producto',				message: 'El Producto de la Cuenta es requerido'},
	     {type: 'presence', field: 'monedaCuenta',			message: 'El Tipo de Moneda de la Cuenta es requerido'},
	     {type: 'presence', field: 'montoInicial',			message: 'El Monto Inicial es requerido'}, 
	     {type: 'presence', field: 'operacion',				message: 'El Tipo de Operación es requerido'},
	     {type: 'presence', field: 'oficioReqOpe',			message: 'El Oficio del Requerimiento es requerido'},
	     {type: 'presence', field: 'fecharRequerimiento',	message: 'La Fecha del Requerimiento es requerida'},
	     {type: 'presence', field: 'fechaAplicacion',		message: 'La Fecha de Aplicación es requerida'},
	     {type: 'presence', field: 'montoOperacion',		message: 'El Monto de la Operación es requerido'},
	     {type: 'presence', field: 'monedaOperacion',		message: 'El Tipo de Moneda de la Operación es requerido'},
	     {type: 'presence', field: 'saldoOperacion',		message: 'El Saldo de la Operación es requerido'}    
 	]		
	
});